FireMotD
=> Revert "Fix for ubuntu showing "DISTRIB_ID=Ubuntu""

FireMotD, readme.md
- Many changes on help info
- Many changes on readme.md
- Fixes for Release information
- Fixes for Platform information
- Fixes for systems without (yum|apt-get) information file
- Some other small stuff
- Adds locale variables (tested on a pt_BR.iso88591 Amazon Linux server, failed without the vars)
=> Fixes and cosmetic changes

FireMotD, readme.md
Gets internet IP on Amazon EC2 instances, since the LAN IP is useless in this case. Need curl OR wget, but does nothing if they are not present in the system (on which case the LAN IP is maintained). Does not require external site for checking IP (uses an Amazon URL that is internal to their virtual network). Changed version number.
=> Gets internet IP on Amazon EC2; Performance fix; Detects Xen Hypervisors;

FireMotD, readme.md
Feel free to change it if you want. This is my first try. I wanted an orange theme, then tried a green one, but it is hard to make anything with the few colours available. So I just made a gray one :) LOL
=> Gray theme

FireMotD
Just found out that there's only MySQL, so quickly added PSQL support.
=> Added PostgreSQL support

FireMotD
Seem to work for OpenVZ and KVM, might work for something else.
=> Additional way to determine platform

FireMotD
=> Added nginx support

FireMotD
Hey @willemdh,
would be great if we could merge this and the other PR quickly. I need them for a showcase. Thanks! 👍
=> Add Pine A64 as supported platform

FireMotD
=> Added support for Core/Socket count for OpenVZ

FireMotD
Should fix #33 and partially fix #28 (only the part related to convert -1 to unlimited)
=> Get latest memory_limit from php.ini and convert -1 to Unlimited

FireMotD
Should fix this offset bug:
And add comma there:
=> Fixed Postgres text offset and added comma separator for PHP details

FireMotD
The original line was a typo I guess.
=> Correct and move sysctl WriteLog line

FireMotD
Might be a bit cleaner than the solution in https://github.com/willemdh/FireMotD/issues/44 - doesn't alter functionality.
=> Improve PhpMaxMemory generation

FireMotD
Should supposedly resolve #26 
Might require some testing before merge.
This is how it shows on my VPS
=> Added HideVersion option + slightly corrected text offsets

FireMotD
=> Test with dev branch

FireMotD
I guess not that many OpenVZ users, so not many people noticed this.
This should fix it.
=> Fix for OpenVZ jq check typo (Cpu core count)

FireMotD, readme.md
Basically #18. Only added support for apt.
Might require some testing from @ThomDietrich
=> Optional skip for package update (only for apt currently)

FireMotD
=> Changed to show real memory usage

FireMotD
no big changes. Fix for #70 and more space for fields in 16 color themes
=> v8.08.171007 => Bugfix

FireMotD
@dimon222 @ThomDietrich 
Please review, fix for https://github.com/willemdh/FireMotD/issues/75
=> Fix for free on CentOS 6, readable VersionCompare

FireMotD
=> Fix variable typo nginxVersion

FireMotD
Some code should be added for apt and zypper, but this works fro yum:
```
./FireMotD -T Red
2017-12-08 19:32:09,238: FireMotD: Error: Unable to detect jq. Please install.
```
```
./FireMotD -v -T Red
2017-12-08 19:31:59,208: FireMotD: Info: Verbose execution.
2017-12-08 19:31:59,531: FireMotD: Info: Detected openssh-clients
2017-12-08 19:31:59,820: FireMotD: Info: Detected bc
2017-12-08 19:32:00,121: FireMotD: Info: Detected sysstat
2017-12-08 19:32:00,533: FireMotD: Error: Unable to detect jq. Please install.
```
Please test if it does'nt result in any issues on apt system.
=> check for dependencies

FireMotD, FireMotD-reference.json, FireMotD.json
Please review this change. It's the first step in moving the json config out of the FireMotD. script. That way, we can make different config jsons and allow users to only select a few items out of the full reference. it's just a PoC for now, ideas are welcome. :)
=> First step towards external config files

FireMotD
=> Dev willem installer

FireMotD
=> orange theme fix

FireMotD, readme.md, themes/FireMotD-theme-Blanco.json, themes/FireMotD-theme-Eline.json
=> Willemdh fixes

FireMotD
Mainly typos and shellcheck recommendations
=> Shellcheck fixes

FireMotD
As moreutils / sponge does not seem supported yet with CentOS 8, I deccided to switch to a temp file. One less dependency doesn't seem so bad.
=> Dev willem unsponge
